version: "3.9"

services:
  some-scylla:
    image: scylladb/scylla
    container_name: some-scylla
    # ports:
    #   - "9042:9042"

  some-scylla2:
    image: scylladb/scylla
    container_name: some-scylla2
    command: --seeds=some-scylla

  some-scylla3:
    image: scylladb/scylla
    container_name: some-scylla3
    command: --seeds=some-scylla

  some-scylla4:
    image: scylladb/scylla
    container_name: some-scylla4
    command: --seeds=some-scylla

  some-scylla5:
    image: scylladb/scylla
    container_name: some-scylla5
    command: --seeds=some-scylla

  redis:
    restart: unless-stopped
    image: redis
    ports:
      - "6379:6379"

  scrape-service:
    build:
      context: .
    command: python /service/scrape_requests/serve.py --max_workers 20
    ports:
      - "50051:50051"
    networks:
      - microservices

  # video-scrape:
  #   build:
  #     context: .
  #   command: python /service/scrape_requests/video_scrape_requests.py
  #   ports:
  #     - "50051:50051"
  #   networks:
  #     - microservices

  # channel-scrape:
  #   build:
  #     context: .
  #   command: python /service/scrape_requests/channel_scrape_requests.py
  #   ports:
  #     - "50052:50051"
  #   networks:
  #     - microservices

networks:
  microservices:
