version: "3.9"

services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - "6379:6379"

  scrape-service:
    build:
      context: .
    command: python /service/scrape_requests/serve.py --max_workers 25
    # ports:
    #   - "50051:50051"
    expose:
      - 50051
    secrets:
      - nginx.cert
      - nginx.key
    # depends_on:
    #   - nginx-reverseproxy
    networks:
      - microservices

  nginx-reverseproxy:
    image: nginx:1.13.11
    ports:
      - 127.0.0.1:1443:1443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    secrets:
      - nginx.cert
      - nginx.key
    depends_on:
      - scrape-service
    networks:
      - microservices

networks:
  microservices:
    external: true

secrets:
  nginx.cert:
    file: ./cert/nginx.cert
  nginx.key:
    file: ./cert/nginx.key
