"""implement queryResult model #2

Revision ID: 0d0d773e8cb1
Revises: 76aa357e3ef2
Create Date: 2022-05-06 02:19:27.060460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0d773e8cb1'
down_revision = '76aa357e3ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
