"""implement queryResult model

Revision ID: 76aa357e3ef2
Revises: 
Create Date: 2022-05-06 02:15:28.342187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76aa357e3ef2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_result',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_video_association',
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('query_result_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['query_result_id'], ['query_result.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.UniqueConstraint('video_id', 'query_result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_video_association')
    op.drop_table('query_result')
    # ### end Alembic commands ###
