"""add scrapeJob and videoCategory models, and json files

Revision ID: be271118e311
Revises: 
Create Date: 2022-06-18 22:58:41.585627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be271118e311'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_job',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('nupdate', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('channel', sa.Column('nvideo', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'query_result', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'query_result', type_='unique')
    op.drop_column('channel', 'nvideo')
    op.drop_table('scrape_job')
    op.drop_table('video_category')
    # ### end Alembic commands ###
