# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrape_requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scrape_requests.proto\"M\n\rScrapeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12!\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x0f.ScrapeCategory\x12\r\n\x05value\x18\x03 \x01(\t\"N\n\x0cScrapeResult\x12\n\n\x02id\x18\x01 \x01(\t\x12!\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x0f.ScrapeCategory\x12\x0f\n\x07success\x18\x03 \x01(\x08\"6\n\x0eScrapeResponse\x12$\n\rscrapeResults\x18\x01 \x03(\x0b\x32\r.ScrapeResult*5\n\x0eScrapeCategory\x12\x0b\n\x07\x43HANNEL\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\x0b\n\x07\x43OMMENT\x10\x02\x32\x36\n\tScrapings\x12)\n\x06Scrape\x12\x0e.ScrapeRequest\x1a\x0f.ScrapeResponseb\x06proto3')

_SCRAPECATEGORY = DESCRIPTOR.enum_types_by_name['ScrapeCategory']
ScrapeCategory = enum_type_wrapper.EnumTypeWrapper(_SCRAPECATEGORY)
CHANNEL = 0
VIDEO = 1
COMMENT = 2


_SCRAPEREQUEST = DESCRIPTOR.message_types_by_name['ScrapeRequest']
_SCRAPERESULT = DESCRIPTOR.message_types_by_name['ScrapeResult']
_SCRAPERESPONSE = DESCRIPTOR.message_types_by_name['ScrapeResponse']
ScrapeRequest = _reflection.GeneratedProtocolMessageType('ScrapeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPEREQUEST,
  '__module__' : 'scrape_requests_pb2'
  # @@protoc_insertion_point(class_scope:ScrapeRequest)
  })
_sym_db.RegisterMessage(ScrapeRequest)

ScrapeResult = _reflection.GeneratedProtocolMessageType('ScrapeResult', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESULT,
  '__module__' : 'scrape_requests_pb2'
  # @@protoc_insertion_point(class_scope:ScrapeResult)
  })
_sym_db.RegisterMessage(ScrapeResult)

ScrapeResponse = _reflection.GeneratedProtocolMessageType('ScrapeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCRAPERESPONSE,
  '__module__' : 'scrape_requests_pb2'
  # @@protoc_insertion_point(class_scope:ScrapeResponse)
  })
_sym_db.RegisterMessage(ScrapeResponse)

_SCRAPINGS = DESCRIPTOR.services_by_name['Scrapings']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCRAPECATEGORY._serialized_start=240
  _SCRAPECATEGORY._serialized_end=293
  _SCRAPEREQUEST._serialized_start=25
  _SCRAPEREQUEST._serialized_end=102
  _SCRAPERESULT._serialized_start=104
  _SCRAPERESULT._serialized_end=182
  _SCRAPERESPONSE._serialized_start=184
  _SCRAPERESPONSE._serialized_end=238
  _SCRAPINGS._serialized_start=295
  _SCRAPINGS._serialized_end=349
# @@protoc_insertion_point(module_scope)
