apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-reverseproxy
  name: nginx-reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-reverseproxy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices: "true"
        io.kompose.service: nginx-reverseproxy
    spec:
      containers:
        - image: nginx:1.13.11
          name: nginx-reverseproxy
          ports:
            - containerPort: 1443
          resources: {}
          volumeMounts:
            - mountPath: /run/secrets/nginx.cert
              name: nginx.cert
            - mountPath: /run/secrets/nginx.key
              name: nginx.key
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-reverseproxy-claim0
      restartPolicy: Always
      volumes:
        - name: nginx.cert
          secret:
            items:
              - key: nginx.cert
                path: nginx.cert
            secretName: nginx.cert
        - name: nginx.key
          secret:
            items:
              - key: nginx.key
                path: nginx.key
            secretName: nginx.key
        - name: nginx-reverseproxy-claim0
          persistentVolumeClaim:
            claimName: nginx-reverseproxy-claim0
status: {}
