apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./kubernetes
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: scrape-service
  name: scrape-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scrape-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./kubernetes
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/microservices: "true"
        io.kompose.service: scrape-service
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - |
              python /service/scrape_requests/serve.py --max_workers 25
              # python /service/scrape_requests/serve.py --max_workers 25 --secure
              # python -c "while True: pass"
          image: ghcr.io/paulbroek/youtube-recommender:main
          # image: ghcr.io/paulbroek/youtube-recommender:test
          # image: ghcr.io/paulbroek/youtube-recommender:latest
          name: scrape-service
          ports:
            - containerPort: 50051
          resources: {}
          volumeMounts:
            - name: nginx-cert-secret
              mountPath: /run/secrets_from/nginx.cert
              readOnly: true
            - name: nginx-key-secret
              mountPath: /run/secrets_from/nginx.key
              readOnly: true
            - name: postgres-cfg-secret
              mountPath: /run/secrets_from/postgres.cfg
              # mountPath: /usr/local/lib/python3.9/site-packages/youtube_recommender/config/postgres.cfg
              readOnly: true
          # hack: copy secrets file to desired path. k8s doesn't allow to mount a file to a specific file location
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp /run/secrets_from/nginx.cert/secret.file /run/secrets/nginx.cert
                    cp /run/secrets_from/nginx.key/secret.file /run/secrets/nginx.key
                    cp /run/secrets_from/postgres.cfg/secret.file /run/secrets/postgres.cfg
          env:
            - name: RELEASE_MODE
              value: PRODUCTION
          imagePullPolicy: Always

      restartPolicy: Always
      volumes:
        - name: nginx-cert-secret
          secret:
            # items:
            #   - key: nginx-cert
            #     path: nginx.cert
            secretName: nginx-cert-secret
        - name: nginx-key-secret
          secret:
            # items:
            #   - key: nginx-key
            #     path: nginx.key
            secretName: nginx-key-secret
        - name: postgres-cfg-secret
          secret:
            secretName: postgres-cfg-secret
status: {}
