name: Auto merge pull request

# TODO: will not trigger when pr was created by action / bot
on:
  pull_request:
    # branches: ["test", "main"]
    # types: [opened]
    types: [labeled]
    # option below is safer than `types: [opened]`, since auto created prs won't trigger this workflow
    # labeled: ["ready-to-merge"]

jobs:
  auto-merge-pull-request:
    if: ${{ github.event.label.name == 'ready-to-merge' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: auto merge pull request
        run: |
          # get last pull-request id
          # TODO: not safe when multiple prs are opened
          prId=$(gh pr list -tail -n 1 | awk '{print $1}')
          # auto-merge pull-request
          gh pr merge $prId --auto -md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
