name: Create pull request

on:
  push:
    branches: ["test"]

  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          # token: ${{ secrets.GH_ACCESS_TOKEN }}
          branch: pr-branch
          base: main
          # commit-message:
          title: "Merge test into main"
          body: |
            Created by GitHub action
          labels: |
            ready-to-merge
            automated pr
          delete-branch: false

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      # - name: create pull request
      #   run: |
      #     gh auth login --with-token ${{ secrets.GH_ACCESS_TOKEN }}
      #     # gh label create -f ready-to-merge
      #     gh pr create -B main -H test -l ready-to-merge --title 'Merge test into main' --body 'Created by Github action'
      #   env:
      #     # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     # now workflow can trigger other workflows, create access token first
      #     # See: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
      #     GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
